timezone: America/New_York
  
tasks:
  - title: Do Something
    description: It does something very important.
    interval: every 10 seconds
    type: run
    image: mhart/alpine-node:8.6.0
    command: ["ls", "-al"]
    overlap: false
    enabled: false
    execute_on_start: false
  - title: List running processes
    description: It lists running processes.
    interval: "* */1 * * *"
    type: run
    image: mhart/alpine-node:8.6.0
    # container: upbeat_mahavira
    command: ["ps", "aux"]
    overlap: false
    enabled: true
    execute_on_start: false
    random_delay: 20
    # email: foo@localhost.site
    # batch_email_interval: 3
email:
  smtp:
    from_name: TickTock
    from_email: ticktock@localhost.site
    config:
      host: maildev
      port: 25
      secure: false
      tls:
        secure: false
        ignoreTLS: true
        rejectUnauthorized: false