version: '3.4'

services:

  ticktock:
    image: tkambler/ticktock
    build:
      context: .
    ports:
      - "80:80"
    entrypoint: nodemon start.js
    volumes:
      - .:/opt/ticktock
      - ./example/notifications:/opt/ticktock/notifications
      - ./example/config.yml:/config.yml
      - /var/run/docker.sock:/var/run/docker.sock

  maildev:
    image: djfarrelly/maildev
    ports:
      - "1080:80"